# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/akamlah/ollama-gui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/akamlah/ollama-gui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/akamlah/ollama-gui/CMakeFiles /Users/akamlah/ollama-gui//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/akamlah/ollama-gui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ollamagui

# Build rule for target.
ollamagui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ollamagui
.PHONY : ollamagui

# fast build rule for target.
ollamagui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/build
.PHONY : ollamagui/fast

#=============================================================================
# Target rules for targets named ollamagui_autogen

# Build rule for target.
ollamagui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ollamagui_autogen
.PHONY : ollamagui_autogen

# fast build rule for target.
ollamagui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui_autogen.dir/build.make CMakeFiles/ollamagui_autogen.dir/build
.PHONY : ollamagui_autogen/fast

OllamaGui/src/api/Api.o: OllamaGui/src/api/Api.cpp.o
.PHONY : OllamaGui/src/api/Api.o

# target to build an object file
OllamaGui/src/api/Api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/api/Api.cpp.o
.PHONY : OllamaGui/src/api/Api.cpp.o

OllamaGui/src/api/Api.i: OllamaGui/src/api/Api.cpp.i
.PHONY : OllamaGui/src/api/Api.i

# target to preprocess a source file
OllamaGui/src/api/Api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/api/Api.cpp.i
.PHONY : OllamaGui/src/api/Api.cpp.i

OllamaGui/src/api/Api.s: OllamaGui/src/api/Api.cpp.s
.PHONY : OllamaGui/src/api/Api.s

# target to generate assembly for a file
OllamaGui/src/api/Api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/api/Api.cpp.s
.PHONY : OllamaGui/src/api/Api.cpp.s

OllamaGui/src/main.o: OllamaGui/src/main.cpp.o
.PHONY : OllamaGui/src/main.o

# target to build an object file
OllamaGui/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/main.cpp.o
.PHONY : OllamaGui/src/main.cpp.o

OllamaGui/src/main.i: OllamaGui/src/main.cpp.i
.PHONY : OllamaGui/src/main.i

# target to preprocess a source file
OllamaGui/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/main.cpp.i
.PHONY : OllamaGui/src/main.cpp.i

OllamaGui/src/main.s: OllamaGui/src/main.cpp.s
.PHONY : OllamaGui/src/main.s

# target to generate assembly for a file
OllamaGui/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/main.cpp.s
.PHONY : OllamaGui/src/main.cpp.s

OllamaGui/src/ui/Chat.o: OllamaGui/src/ui/Chat.cpp.o
.PHONY : OllamaGui/src/ui/Chat.o

# target to build an object file
OllamaGui/src/ui/Chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/Chat.cpp.o
.PHONY : OllamaGui/src/ui/Chat.cpp.o

OllamaGui/src/ui/Chat.i: OllamaGui/src/ui/Chat.cpp.i
.PHONY : OllamaGui/src/ui/Chat.i

# target to preprocess a source file
OllamaGui/src/ui/Chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/Chat.cpp.i
.PHONY : OllamaGui/src/ui/Chat.cpp.i

OllamaGui/src/ui/Chat.s: OllamaGui/src/ui/Chat.cpp.s
.PHONY : OllamaGui/src/ui/Chat.s

# target to generate assembly for a file
OllamaGui/src/ui/Chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/Chat.cpp.s
.PHONY : OllamaGui/src/ui/Chat.cpp.s

OllamaGui/src/ui/Dialog.o: OllamaGui/src/ui/Dialog.cpp.o
.PHONY : OllamaGui/src/ui/Dialog.o

# target to build an object file
OllamaGui/src/ui/Dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/Dialog.cpp.o
.PHONY : OllamaGui/src/ui/Dialog.cpp.o

OllamaGui/src/ui/Dialog.i: OllamaGui/src/ui/Dialog.cpp.i
.PHONY : OllamaGui/src/ui/Dialog.i

# target to preprocess a source file
OllamaGui/src/ui/Dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/Dialog.cpp.i
.PHONY : OllamaGui/src/ui/Dialog.cpp.i

OllamaGui/src/ui/Dialog.s: OllamaGui/src/ui/Dialog.cpp.s
.PHONY : OllamaGui/src/ui/Dialog.s

# target to generate assembly for a file
OllamaGui/src/ui/Dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/Dialog.cpp.s
.PHONY : OllamaGui/src/ui/Dialog.cpp.s

OllamaGui/src/ui/MainWindow.o: OllamaGui/src/ui/MainWindow.cpp.o
.PHONY : OllamaGui/src/ui/MainWindow.o

# target to build an object file
OllamaGui/src/ui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/MainWindow.cpp.o
.PHONY : OllamaGui/src/ui/MainWindow.cpp.o

OllamaGui/src/ui/MainWindow.i: OllamaGui/src/ui/MainWindow.cpp.i
.PHONY : OllamaGui/src/ui/MainWindow.i

# target to preprocess a source file
OllamaGui/src/ui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/MainWindow.cpp.i
.PHONY : OllamaGui/src/ui/MainWindow.cpp.i

OllamaGui/src/ui/MainWindow.s: OllamaGui/src/ui/MainWindow.cpp.s
.PHONY : OllamaGui/src/ui/MainWindow.s

# target to generate assembly for a file
OllamaGui/src/ui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/MainWindow.cpp.s
.PHONY : OllamaGui/src/ui/MainWindow.cpp.s

OllamaGui/src/ui/SelectModel.o: OllamaGui/src/ui/SelectModel.cpp.o
.PHONY : OllamaGui/src/ui/SelectModel.o

# target to build an object file
OllamaGui/src/ui/SelectModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/SelectModel.cpp.o
.PHONY : OllamaGui/src/ui/SelectModel.cpp.o

OllamaGui/src/ui/SelectModel.i: OllamaGui/src/ui/SelectModel.cpp.i
.PHONY : OllamaGui/src/ui/SelectModel.i

# target to preprocess a source file
OllamaGui/src/ui/SelectModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/SelectModel.cpp.i
.PHONY : OllamaGui/src/ui/SelectModel.cpp.i

OllamaGui/src/ui/SelectModel.s: OllamaGui/src/ui/SelectModel.cpp.s
.PHONY : OllamaGui/src/ui/SelectModel.s

# target to generate assembly for a file
OllamaGui/src/ui/SelectModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/OllamaGui/src/ui/SelectModel.cpp.s
.PHONY : OllamaGui/src/ui/SelectModel.cpp.s

ollamagui_autogen/SJC63UBMP2/qrc_resources.o: ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.o
.PHONY : ollamagui_autogen/SJC63UBMP2/qrc_resources.o

# target to build an object file
ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.o
.PHONY : ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.o

ollamagui_autogen/SJC63UBMP2/qrc_resources.i: ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.i
.PHONY : ollamagui_autogen/SJC63UBMP2/qrc_resources.i

# target to preprocess a source file
ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.i
.PHONY : ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.i

ollamagui_autogen/SJC63UBMP2/qrc_resources.s: ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.s
.PHONY : ollamagui_autogen/SJC63UBMP2/qrc_resources.s

# target to generate assembly for a file
ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.s
.PHONY : ollamagui_autogen/SJC63UBMP2/qrc_resources.cpp.s

ollamagui_autogen/mocs_compilation.o: ollamagui_autogen/mocs_compilation.cpp.o
.PHONY : ollamagui_autogen/mocs_compilation.o

# target to build an object file
ollamagui_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/ollamagui_autogen/mocs_compilation.cpp.o
.PHONY : ollamagui_autogen/mocs_compilation.cpp.o

ollamagui_autogen/mocs_compilation.i: ollamagui_autogen/mocs_compilation.cpp.i
.PHONY : ollamagui_autogen/mocs_compilation.i

# target to preprocess a source file
ollamagui_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/ollamagui_autogen/mocs_compilation.cpp.i
.PHONY : ollamagui_autogen/mocs_compilation.cpp.i

ollamagui_autogen/mocs_compilation.s: ollamagui_autogen/mocs_compilation.cpp.s
.PHONY : ollamagui_autogen/mocs_compilation.s

# target to generate assembly for a file
ollamagui_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ollamagui.dir/build.make CMakeFiles/ollamagui.dir/ollamagui_autogen/mocs_compilation.cpp.s
.PHONY : ollamagui_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ollamagui_autogen"
	@echo "... ollamagui"
	@echo "... OllamaGui/src/api/Api.o"
	@echo "... OllamaGui/src/api/Api.i"
	@echo "... OllamaGui/src/api/Api.s"
	@echo "... OllamaGui/src/main.o"
	@echo "... OllamaGui/src/main.i"
	@echo "... OllamaGui/src/main.s"
	@echo "... OllamaGui/src/ui/Chat.o"
	@echo "... OllamaGui/src/ui/Chat.i"
	@echo "... OllamaGui/src/ui/Chat.s"
	@echo "... OllamaGui/src/ui/Dialog.o"
	@echo "... OllamaGui/src/ui/Dialog.i"
	@echo "... OllamaGui/src/ui/Dialog.s"
	@echo "... OllamaGui/src/ui/MainWindow.o"
	@echo "... OllamaGui/src/ui/MainWindow.i"
	@echo "... OllamaGui/src/ui/MainWindow.s"
	@echo "... OllamaGui/src/ui/SelectModel.o"
	@echo "... OllamaGui/src/ui/SelectModel.i"
	@echo "... OllamaGui/src/ui/SelectModel.s"
	@echo "... ollamagui_autogen/SJC63UBMP2/qrc_resources.o"
	@echo "... ollamagui_autogen/SJC63UBMP2/qrc_resources.i"
	@echo "... ollamagui_autogen/SJC63UBMP2/qrc_resources.s"
	@echo "... ollamagui_autogen/mocs_compilation.o"
	@echo "... ollamagui_autogen/mocs_compilation.i"
	@echo "... ollamagui_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

